### ISSUE TITLE
Mehr dummy Inhalte für sql Beispiel generieren

### ISSUE THREAD

**Issue by Lockenjoe92** [Lockenjoe92/UKT-COVID19-Helpermanagement#10]

**Comment by David100mark** [comment]
für alle Tables?
Dummy user als csv zum parsen hab ich schon 5 Stück geschrieben

**Comment by Lockenjoe92** [comment]
Coole Idee! Dann hau mal rüber bzw du kannst den Code von Leo ja auf dem netcup-Server ausführen, dann hätten wir auch gleich den Live Test:)

**Comment by David100mark** [comment]
Hat Leo schon,
Ich leg für den Rest noch dummys an

**Comment by ldrocket** [comment]
Weitere Dummyinhalte stehen in der Fachschaftscloud.
