### ISSUE TITLE
Benutzer von der Suche ausnehmen

### ISSUE THREAD

**Issue by ldrocket** [Lockenjoe92/UKT-COVID19-Helpermanagement#101]
Vor dem Release müssen manche Benutzer von der Einteilung ausgenommen werden. Das betrifft z.B. Taskforce-Benutzer, Admins, etc. Sonst werden sie mit in der Übersicht angezeigt.

Die IDs der Benutzer müssen eingetragen werden ab Zeile 190 in der Datei `/mission_functions/mission_manage.php`. Für jeden Benutzer muss es eine Zeile geben.

Siehe:

https://github.com/Lockenjoe92/UKT-COVID19-Helpermanagement/blob/master/mission_functions/mission_manage.php#L189

**Comment by SixByNine42** [comment]
Sollte das nicht über die Datenbank gehen? Taskforce-Benutzer sind doch über einen Datenbankeintrag zu erkennen

**Comment by ldrocket** [comment]
@Lockenjoe92 @David100mark Reicht es, wenn ausschließlich die Taskforce-Nutzer von der Suche ausgenommen werden? Dann kann ich das auch über die Datenbank regeln. Sollten andere Nutzer ausgenommen werden müssen, geht das über den Code.

**Comment by David100mark** [comment]
Reicht nur für Taskforce user

**Comment by Lockenjoe92** [comment]
Jap nur taskforce Nutzer reicht - sonst gibt es aktuell keine anderen Nutzertypen:)
