### ISSUE TITLE
einteilung_bearbeiten.php einrichten 

### ISSUE THREAD

**Issue by Lockenjoe92** [Lockenjoe92/UKT-COVID19-Helpermanagement#103]
Hier wird das Formular angezeigt 

-> bekommt über $_GET den Parameter id_einteilung die zu ladende Einteilung mitgeteilt
-> zeigt Metadaten an

-> bearbeitbar sind Mind. Begin/Ende/als_quali
-> Alternativ komplett löschen

-> parser bearbeitet dB Eintrag entsprechend und sendet Mail an den Helfer

**Comment by JulianFlesch** [comment]
Komme da allerdings wirklich erst morgen zu .. Das würde dann hoffentlich Mittwoch (spät) abends MEZ online gehen.

**Comment by Lockenjoe92** [comment]
Top das passt danke dir!:) Denke der Rest vom Tool steht vorher auch nicht und zur not könnte man die ersten Bearbeitungen auch noch händisch in der DB machen wenns wär.

**Comment by David100mark** [comment]
Mailvorlagen dafür sind angelegt
einteilung_bearbeitet und einteilung_gelöscht #168

**Comment by JulianFlesch** [comment]
Es gibt jetzt einteilungen.php die alle einteilungen listet.
Einzelne Einteilungen können mit den parametern ?userID=<id> and ?eintID=<id> angezeigt und bearbeitet werden.

Löschen ist in der Liste un der Bearbeitungsansicht möglich

**Comment by Lockenjoe92** [comment]
Stark Danke dir!!:)

**Comment by JulianFlesch** [comment]
Welche Mails müssen dann noch genau verschickt werden? Und wie geht das?

**Comment by Lockenjoe92** [comment]
einteilung_bearbeitet und einteilung_gelöscht
- die Vorlagen dazu hat David angelegt.

Am besten du schaust dir mal zB bei add_user() den Code dazu an. Ist ne fertige Funktion send_mail() (glaub ich) die als Parameter did E-Mail des Users nimmt + die Vorlage die sie aus mailvorlagen.xml laden soll und ein Array aus Parametern für Textbausteinen die von der Funktion dann automatisch eingebaut werden.

Letzteres funktioniert mit String_replace. Die Variablen sind im Text mit [variable] hinterlegt. Dh du musst der Funktion ein Array schicken, dass wir folgt aussieht:
”[vorname]“=>$VornameUser

**Comment by Lockenjoe92** [comment]
Die Funktion heißt mail_senden()

**Comment by JulianFlesch** [comment]
Das sollte damit geschlossen sein
