### ISSUE TITLE
Link auf Einteilung bearbeiten von Helferliste der Stellen implementieren 

### ISSUE THREAD

**Issue by Lockenjoe92** [Lockenjoe92/UKT-COVID19-Helpermanagement#105]
Taskforce view -> stellenmanagemnt -> helferliste der aktuell eingeteilten Helfer

-> Link Button der auf die bearbeiten Seite zeigt

**Comment by JulianFlesch** [comment]
Ich verstehe das so: 
* Eingeteilte Helfer sinnvoll anzeigen
* jede Einteilung verlinkt auf die Bearbeitungsseite dieser Einteilung

Gibt es die Bearbeitungsseite schon?

**Comment by Lockenjoe92** [comment]
genau - ich dachte wenn du zB in deinem table die Helfer anzeigst, kannst du ein Feld mit "Einteilungen" machen - am einfachsten steht dann einfach da der Name der eingeteilten Stelle - und wenn man dahinter n knopf hat um genau diese Einteilung zu editieren, wäre das für den Workflow denke ich schon ausreichend!:)

**Comment by Lockenjoe92** [comment]
ich mache in der Übersicht der erstellten stelle auch so eine Helferliste die sich aus den aktiven Einteilungen generiert und würde von dort aus auch dahin linken

**Comment by Lockenjoe92** [comment]
und negativ - die Seite existiert bislang noch nicht - kannst dich also voll und ganz austoben!:)
