### ISSUE TITLE
Link auf Einteilung bearbeiten . php für Helfereinteilungen in user_bearbeiten Ansicht 

### ISSUE THREAD

**Issue by Lockenjoe92** [Lockenjoe92/UKT-COVID19-Helpermanagement#106]

**Comment by Lockenjoe92** [comment]
Idee wäre folgende:
Auf der User bearbeiten Seite findet sich ne Liste mit Einteilungen -> hier dann nen edit-Knopf mit Link auf die einteilung_bearbeiten Seite

**Comment by JulianFlesch** [comment]
Die Liste mit Einteilungen für einen User (z.b mit der ID 10) gibt es schon unter /einteilungen.php?userID=10

Wenn ein User nur eine Einteilung hat, öffnet sich hier ansonsten direkt die Bearbeitungsseite. Auf diese Seite wird von der Helferliste aus verlinkt. 
Können wir das damit schließen?

**Comment by Lockenjoe92** [comment]
Das klingt alles sehr gut👍🏻

**Comment by SixByNine42** [comment]
Link auf der User bearbeiten Seite zu den Einteilungen des Helfers hinzugefügt.
Sollte wenigstens die Anzahl der Einteilungen noch auf der User bearbeiten Seite angezeigt werden?

**Comment by Lockenjoe92** [comment]
Fände ich eine nützliche Information:)

**Comment by SixByNine42** [comment]
Sollen alle Einteilungen angezeigt werden, oder werden bereits abgeleistete ausgeschlossen?

**Comment by Lockenjoe92** [comment]
Gute Frage - ich würde spontan erstmal nur aktive sagen, oder @david100mark?

**Comment by David100mark** [comment]
Naja aktiv sollte ja immer nur eine sein oder? Damit wäre ein Zähler für alle Einteilungen besser :)

**Comment by JulianFlesch** [comment]
Zum zählen aller Einteilungen gibts sogar schon die Funktion `num_einteilungen_for_user($userID)`

**Comment by Lockenjoe92** [comment]
Hervorragend dann ist das ja super easy:)
