### ISSUE TITLE
Es werden keine Emails versendet

### ISSUE THREAD

**Issue by David100mark** [Lockenjoe92/UKT-COVID19-Helpermanagement#107]
Weder beim hochladen einer CSV noch beim Anlegen einer Stelle werden Emails versendet.

Beim CSV-Upload wird der Nutzer angelegt aber keine Email versendet

**Comment by ldrocket** [comment]
Auf welcher URL hast du das getestet? Ich habe festgestellt, dass die Mails auf der Master-Playground bei netcup recht spät ankommen. Daher bitte auch auf der realen Domain testen, da kommen sie sofort an.

**Comment by ldrocket** [comment]
Habe es gerade nochmal auf der zukünftigen Domain getestet, da funktioniert alles problemlos. Hängt wohl mit netcup zusammen.
