### ISSUE TITLE
504 Gateway Fehler beim parsen der CSV

### ISSUE THREAD

**Issue by David100mark** [Lockenjoe92/UKT-COVID19-Helpermanagement#108]
Beim Parsen einer längeren CSV kommt es zu einem  504 Gateway Fehler.

**Comment by bpcurse** [comment]
504 ist ein timeout. Nach welcher Zeit tritt das auf?

**Comment by David100mark** [comment]
ich glaube knapp 15 sekunden ?

**Comment by bpcurse** [comment]
Wenn keine viel längeren Zeiten zu erwarten sind, könnte man einfach den timeout hochsetzen, z.B. mit set_time_limit(), direkt über die php.ini Datei oder gleich aufteilen und chunks verarbeiten?

**Comment by David100mark** [comment]
Also das war jetzt ne CSV mit 20 Zeilen
Wir werden eine mit circa 9000-1000 hochladen 😁
________________________________

**Comment by SixByNine42** [comment]
Kann jemand einen PHP-profiler, z.B. Xdebug, auf seinem Server installieren und mal das Csv-parsen profilen?
Mit XDebug kann man auch die Profiling-Ergebnisdatei mit den anderen Entwicklern teilen.

**Comment by ldrocket** [comment]
>Wir werden eine mit circa 9000-1000 hochladen

@David100mark Ich würde die Datei nie in solch großer Form am Stück hochladen. Bitte immer unterteilen und stückweise hochladen (z.B. 100 Zeilen pro Stück).

Auf welcher URL hast dus getestet? Am besten testet dus auf der realen Domain (helfer.fachschaft...), weil die bei einem anderen Hoster liegt und da die Umgebung eine andere ist :) Da gab es bei mir bisher keine Probleme, auch nicht bei 20 Zeilen. Die wurden recht schnell eingelesen. Letztendlich ist der beschriebene Fehler ein Serverfehler, der von der Hostingumgebung abhängt, und kein Programmierfehler.

**Comment by ldrocket** [comment]
Ich habe mit Commit 5f45778 wie besprochen die Hinweise zum Hochladen erweitert. Folgendes ist dabei wichtig:

- Die Datei muss utf-8 kodiert und die Umlaute darin korrekt dargestellt sein.

- Die Zeile mit den Bezeichnern der Spalten (RefNo, Name, email, Tel-No, ...) bitte entfernen, sonst wird sie auch eingelesen und führt zu falschen Einträgen.

- Leere Zeilen, die nur Semikolons enthalten, nach Möglichkeit auch entfernen (ist aber nicht schlimm, falls man welche vergisst, weil die dann übersprungen werden).

- Bitte maximal 50 Datensätze pro Datei hochladen und im Anschluss kontrollieren, ob alle Benutzer in die Datenbank eingefügt wurden. Falls nicht alle eingelesen wurden, bitte händisch korrigieren und für die nachfolgenden Vorgänge weniger Datensätze pro Datei hochladen.
