### ISSUE TITLE
Aufnahme der 2. Qualifikation in die Liste aktiver Qualifikationen

### ISSUE THREAD

**Issue by ldrocket** [Lockenjoe92/UKT-COVID19-Helpermanagement#110]
In der Liste aktiver Qualifikationen werden aktuell nur die Einträge mit `has_qualifications` aufgeführt. Da die CSV-Datei aber auch ein Feld für die 2. Qualifikation hat (`quali2`), müssten die zugehörigen Einträge auch in der Übersicht beachtet werden.

**Comment by SixByNine42** [comment]
Können wir beim Einlesen der csv-Datei nicht alle Qualifikationen aus qali1/2/3 in has_qualifications schreiben?

**Comment by David100mark** [comment]
aus meiner Sicht spräche da nix dagegen :)

**Comment by ldrocket** [comment]
Zusatzquali 1/2/3 ist Freitext, das würde ich nicht mit in `has_qualifications` übernehmen. Die 2. Quali kann ich mit übernehmen, aber dann ist später keine Unterscheidung mehr möglich, falls das irgendwann mal gewünscht sein sollte. Weil es in den CSV-Dateien zwei Felder gibt (was sich ja jemand aus guten Gründen überlegt hat), ging ich davon aus, dass sie getrennt bleiben sollen.

Sonst können wir es auch erstmal so lassen, wenn Marc noch die kleine Anpassung vornimmt.

**Comment by David100mark** [comment]
das es für Qualis 2 Felder gibt ist nicht wirklich beabsichtigt, sondern der Form der Abfrage geschuldet. Das kann gerne zusammengeführt werden. 
Zusatzquali1/2/3 sollte extra bleiben

**Comment by ldrocket** [comment]
Geschlossen durch 9e73f7a.
