### ISSUE TITLE
Taskforce Mainpage Layout für kleinere Bildschirme optimieren

### ISSUE THREAD

**Issue by Lockenjoe92** [Lockenjoe92/UKT-COVID19-Helpermanagement#118]
Glaube wir sollten die Tabelle nochmal umstellen, damit auch kleinere Desktops damit zurecht kommen. Sonst werden die Buttons unlesbar?

<img width="1440" alt="Bildschirmfoto 2020-04-01 um 13 45 45" src="https://user-images.githubusercontent.com/20751734/78133679-2c0bcb00-741f-11ea-9ea1-4c406a136722.png">

**Comment by David100mark** [comment]
Könnten wir mit flexbox machen, oder?

**Comment by Lockenjoe92** [comment]
Hmn ja oder du ordnest einfach die vier auflist-Funktionen in 2x2? Geht denke ich am schnellsten?😬
