### ISSUE TITLE
Einteilung anlegen - falsche Helferzuordnung im Formular Seite 2

### ISSUE THREAD

**Issue by Lockenjoe92** [Lockenjoe92/UKT-COVID19-Helpermanagement#119]
Die Checkbox um einen User aus der Liste einzuteilen ist mit dem falschen ID-Wert versehen.
-> es sollte in diesem Beispiel nur einen User mit der id 40 geben
-> das ist der Output für die Checkbox: `<input type="checkbox" name="sendto[]" value="39">`

ist da ein Counter verrutscht?:D

**Comment by ldrocket** [comment]
@Lockenjoe92 Mit welchen Kriterien hast du die Suche durchgeführt? Und mit welchen Datenbankeinträgen / auf welcher URL?

**Comment by Lockenjoe92** [comment]
Suche nach Rettungsidenst, Patientennah, Semester 1, „Medizin“, auch ohne Vertrag, Leute in Tübingen

**Comment by Lockenjoe92** [comment]
Ah aber ich hab das auf meinem playground gemacht, nicht master - evtl ist da was an der db anders

**Comment by Lockenjoe92** [comment]
Auf dem Master-playground kommt bei der Suche folgender Error:


Warning
: Invalid argument supplied for foreach() in
/var/www/vhosts/hosting101609.af9a1.netcup.net/ukt-covid-orga-tool-master-playground.marcsprojects.de/mission_functions/mission_manage.php
on line
272

**Comment by ldrocket** [comment]
> Ah aber ich hab das auf meinem playground gemacht, nicht master - evtl ist da was an der db anders

Ja, da ist die Datenbank noch nicht auf dem aktuellen Stand. Auf der Domain bei ALL-INKL werden die IDs korrekt zugeteilt, habs gerade nochmal geprüft.

> Auf dem Master-playground kommt bei der Suche folgender Error:

Danke :) Hier war das Problem, dass leere Werte als solche und nicht als leerer Array abgespeichert wurden. Ist korrigiert.
