### ISSUE TITLE
Security header setzen

### ISSUE THREAD

**Issue by bpcurse** [Lockenjoe92/UKT-COVID19-Helpermanagement#124]

**Comment by ldrocket** [comment]
Bereits erledigt in #71 :)

**Comment by bpcurse** [comment]
@ldrocket Danke dir

Hinzufügen würde ich noch:
- `Content-Security-Policy: default-src 'self'`
- `X-Robots-Tag: none`
- `X-Permitted-Cross-Domain-Policies: none`

**Comment by ldrocket** [comment]
Sehr gerne, vielen Dank :+1: Ich eröffne den anderen Issue wieder und weise ihn dir zu :)
