### ISSUE TITLE
Einteilungen anlegen: Warnung, wenn keine Helfer ausgewählt

### ISSUE THREAD

**Issue by SixByNine42** [Lockenjoe92/UKT-COVID19-Helpermanagement#129]
Einteilungen anlegen sollte nicht möglich sein, wenn im 2. Schritt keine Helfer ausgewählt sind. Ein Hinweis an den Benutzer, dass Helfer ausgewählt werden müssen, wäre hilfreich anstatt der Erfolgsmeldung.
Code: mission_inform_users() in mission_manage.php

**Comment by ldrocket** [comment]
Wenn keine Helfer ausgewählt sind, wird auch keine Einteilung angelegt. Es erscheint nur die Erfolgsmeldung. Werde das aber in Kürze ändern.
