### ISSUE TITLE
Anlegen neuer Einsatzstelle: Eingegebene Daten nicht löschen bei fehlenden Angaben

### ISSUE THREAD

**Issue by SixByNine42** [Lockenjoe92/UKT-COVID19-Helpermanagement#130]
Wenn beim Anlegen einer neuen Einsatzstelle nicht alle Felder ausgefülllt sind, werden die bereits eingegebenen Daten nur als Hintergrund angezeigt und bleiben nicht im Feld.

Code: generate_add_location_form() in locations.php

**Comment by Lockenjoe92** [comment]
Roger passe ich an👍🏻
