### ISSUE TITLE
nur ein Teil der Helfer wird angelegt bei csv import

### ISSUE THREAD

**Issue by David100mark** [Lockenjoe92/UKT-COVID19-Helpermanagement#131]
Datei ist in der Cloud unter testdaten_final.csv

**Comment by ldrocket** [comment]
Um welche User geht es konkret? Die Datei ist leider nicht ganz richtig so, bei manchen Usern ist der Name in zwei Felder aufgeteilt (Vor- und Nachname) und bei anderen steht beides in einem Feld, so wie es sein sollte --> d.h. bei denjenigen, bei denen zwei Felder für den Namen reserviert sind, wird das zweite Feld als E-Mail-Adresse interpretiert und der Import wird übersprungen, ergo der User nicht anlegegt. Du müsstest also nochmal die Datei anpassen :)
