### ISSUE TITLE
Helfer nicht auffindbar - Einteilung anlegen

### ISSUE THREAD

**Issue by Lockenjoe92** [Lockenjoe92/UKT-COVID19-Helpermanagement#133]
Habe versucht Sophie Berger auf UKT Intensiv einzuteilen.

Formular mit allen Optionen auf Ja aufgefüllt aber sie erscheint nicht in der Liste möglicher Helfer.

**Comment by ldrocket** [comment]
Sophie Berger hat keinen Aufenthaltsort in den Metaangaben. Sie kann daher gar nicht gefunden werden.

**Comment by ldrocket** [comment]
Außerdem ist als Fachsemester eingetragen. Das würde der Parser zwar finden, wenn man das als Fachsemester einträgt, aber diese Eingabe machen wahrscheinlich nicht viele :)
