### ISSUE TITLE
Einteilungen anlegen, Qualistandard: nein

### ISSUE THREAD

**Issue by David100mark** [Lockenjoe92/UKT-COVID19-Helpermanagement#138]
Standardwert der Qualifikationen auf nein setzen

**Comment by ldrocket** [comment]
Die Architektur ist aktuell leider genau anders herum: Grundsätzlich kommen immer alle Benutzer in Betracht und werden dann selektiv auf Basis der Kriterien entfernt. D.h. wenn man beim Erstellen "nein" auswählt, dann werden alle diejenigen Benutzer entfernt, die diese Optionen nicht erfüllen. Wenn man alle Einträge standardmäßig auf "nein" setzen würde, müsste man genau anders herum alle Benutzer der Reihe nach hinzufügen, die die Kriterien erfüllen. Das ist auf jeden Fall möglich, aber eher was für eine weitere Version.
