### ISSUE TITLE
Einsatzkategorien werden nicht richtig behandelt

### ISSUE THREAD

**Issue by SixByNine42** [Lockenjoe92/UKT-COVID19-Helpermanagement#139]
Teile des Codes verwenden den userMeta-Eintrag einsatzkategorien, andere Teile has_category:
Beim CSV-Einlesen und Ändern der Helferdaten wird der userMeta-Eintrag 'has_category' verwendet, fast überall sonst "einsatzkategorien".

**Comment by ldrocket** [comment]
`einsatzkategorien` ist der Tabellenname, `has_category` der Key in der Tabelle `user_meta`. Der Wert wird dann als JSON-Array mit den IDs aus der Tabelle `einsatzkategorien` gespeichert.
