### ISSUE TITLE
Startseite - Klick auf "Informationen" führt zurück auf die Seite

### ISSUE THREAD

**Issue by bpcurse** [Lockenjoe92/UKT-COVID19-Helpermanagement#142]

**Comment by ldrocket** [comment]
Ergänzung dazu: Wenn man oben links auf den Titel der Seite klickt, kommt man auch immer auf die `index.php` -- egal, welche Rolle man ist.

**Comment by Lockenjoe92** [comment]
läuft ich baue die navbar Situation-aware, damit sie auf die jeweils "sinnvolle" Startseite geht
