### ISSUE TITLE
Passwort ändern Aufforderung verständlicher machen

### ISSUE THREAD

**Issue by Lockenjoe92** [Lockenjoe92/UKT-COVID19-Helpermanagement#146]
Neues Passwort statt nur "Passwort"

**Comment by bpcurse** [comment]
Bist du da schon dran? Sonst kann ich das gleich mitmachen.

**Comment by Lockenjoe92** [comment]
Negativ hab noch nichts gemacht - darfst du gerne übernehmen!:) danke dir!:)

**Comment by Lockenjoe92** [comment]
Schaue dazu in der helper_view_funtions nach
-> da wird in einer Funktion das Formular generiert:)

**Comment by bpcurse** [comment]
Danke für den Hinweis :+1:

**Comment by Lockenjoe92** [comment]
Hab deine Änderungen übernommen. Danke dir Torsten!:)
