### ISSUE TITLE
user_meta Feld aufenthaltsort wird gelegentlich mit falschen Werten gefüllt

### ISSUE THREAD

**Issue by Lockenjoe92** [Lockenjoe92/UKT-COVID19-Helpermanagement#152]
bei fast allen user ohne Aufenthaltsort steht [] in dem Feld. 
bei manchen (zB für User 80) ist das Feld leer und bringt daher meine Ansicht der Aufenthaltsorte zum Stocken.

Liegt das an fehlerhaften Daten im CSV?

Kann sonst auch einfach den Fall mit ner if-clause vorher abfangen, weiß dann aber nicht ob an anderer stelle ein ähnlichen Problem auftritt?

**Comment by ldrocket** [comment]
Der CSV-Parser trägt immer ein leeres Array (`[]`) ein, falls kein Aufenthaltsort gefunden wurde. Sonst stehen die IDs im Array. Komplett leere Felder darf es eigentlich nicht geben. Vielleicht werden diese Werte beim Bearbeiten der Benutzer "geleert". Ich schaus mir gleich an.

**Comment by ldrocket** [comment]
Bestätigt, beim Bearbeiten werden die Felder komplett geleert. Ich mach ein Issue für Julian auf.

**Comment by ldrocket** [comment]
Siehe #154.

**Comment by Lockenjoe92** [comment]
Alles klar,danke!:)
