### ISSUE TITLE
Schreibweise für "E-Mail" vereinheitlichen

### ISSUE THREAD

**Issue by bpcurse** [Lockenjoe92/UKT-COVID19-Helpermanagement#156]

**Comment by bpcurse** [comment]
@David100mark Das hatte ich mir zugeordnet und fertig bearbeitet, warum machst du die Arbeit doppelt?

**Comment by David100mark** [comment]
sorry, ich war mir eigentlich sicher, dass ich mich auch zugeordnet hatte 🙈🙈

**Comment by bpcurse** [comment]
Nicht behoben durch #168, benötigt #167
