### ISSUE TITLE
Zeige usermeta dse_accept_date

### ISSUE THREAD

**Issue by David100mark** [Lockenjoe92/UKT-COVID19-Helpermanagement#157]
Sowohl in der Helferübersicht, als auch bei der Einteilung sollte dse_accept_date angezeigt werden.

**Comment by ldrocket** [comment]
Im Einteilungsformular wird das Flag nun angezeigt. Im CSV-Parser wird das Feld bereits (für spätere Zwecke oder falls es sich aus den Formularen ergibt) mit angelegt, damit die Reihenfolge stimmt. Mit den aktuellen Daten stimmt das Feld natürlich nicht, hier muss erst #160 erledigt und die Daten neu eingelesen werden.

**Comment by Lockenjoe92** [comment]
Die Abfrage der DSE für User ist implementiert:)

**Comment by JulianFlesch** [comment]
closed in 2f216c0

**Comment by SixByNine42** [comment]
Das aktuelle Datum wird angezeigt, wenn die DSE noch nicht akzeptiert wurde
