### ISSUE TITLE
Doch noch Fehler beim Anlegen einer Einteilung

### ISSUE THREAD

**Issue by Lockenjoe92** [Lockenjoe92/UKT-COVID19-Helpermanagement#158]
![IMAGE 2020-04-01 23:22:30](https://user-images.githubusercontent.com/20751734/78187937-a95f2c00-746f-11ea-8d70-e514cc290eb1.jpg)
![IMAGE 2020-04-01 23:22:33](https://user-images.githubusercontent.com/20751734/78187940-aa905900-746f-11ea-906d-b963f367fbe9.jpg)

**Comment by Lockenjoe92** [comment]
Hat mein Bruder gemacht - falls du noch Infos brauchst, gib bescheid Leo:)

**Comment by ldrocket** [comment]
Das ist alles, weil die Arrays manchmal leer sein können -- das kann ich nicht ändern. Mit #2 verschwinden die Fehler.
