### ISSUE TITLE
Warnings bei Qualifications.php

### ISSUE THREAD

**Issue by David100mark** [Lockenjoe92/UKT-COVID19-Helpermanagement#162]
Warning
: Invalid argument supplied for foreach() in
/www/htdocs/w01a6506/helfer.fachschaftmedizin.de/qualification_functions/qualification_functions.php
on line
503

Warning
: Invalid argument supplied for foreach() in
/www/htdocs/w01a6506/helfer.fachschaftmedizin.de/qualification_functions/qualification_functions.php
on line
503

Warning
: Invalid argument supplied for foreach() in
/www/htdocs/w01a6506/helfer.fachschaftmedizin.de/qualification_functions/qualification_functions.php
on line
503

Warning
: Invalid argument supplied for foreach() in
/www/htdocs/w01a6506/helfer.fachschaftmedizin.de/qualification_functions/qualification_functions.php
on line
503

Warning
: Invalid argument supplied for foreach() in
/www/htdocs/w01a6506/helfer.fachschaftmedizin.de/qualification_functions/qualification_functions.php
on line
503

Warning
: Invalid argument supplied for foreach() in
/www/htdocs/w01a6506/helfer.fachschaftmedizin.de/qualification_functions/qualification_functions.php
on line
503

Warning
: Invalid argument supplied for foreach() in
/www/htdocs/w01a6506/helfer.fachschaftmedizin.de/qualification_functions/qualification_functions.php
on line
503

Warning
: Invalid argument supplied for foreach() in
/www/htdocs/w01a6506/helfer.fachschaftmedizin.de/qualification_functions/qualification_functions.php
on line
503

Warning
: Invalid argument supplied for foreach() in
/www/htdocs/w01a6506/helfer.fachschaftmedizin.de/qualification_functions/qualification_functions.php
on line
503

Warning
: Invalid argument supplied for foreach() in
/www/htdocs/w01a6506/helfer.fachschaftmedizin.de/qualification_functions/qualification_functions.php
on line
503

Warning
: Invalid argument supplied for foreach() in
/www/htdocs/w01a6506/helfer.fachschaftmedizin.de/qualification_functions/qualification_functions.php
on line
503

Warning
: Invalid argument supplied for foreach() in
/www/htdocs/w01a6506/helfer.fachschaftmedizin.de/qualification_functions/qualification_functions.php
on line
503

Warning
: Invalid argument supplied for foreach() in
/www/htdocs/w01a6506/helfer.fachschaftmedizin.de/qualification_functions/qualification_functions.php
on line
503

Warning
: Invalid argument supplied for foreach() in
/www/htdocs/w01a6506/helfer.fachschaftmedizin.de/qualification_functions/qualification_functions.php
on line
503

Warning
: Invalid argument supplied for foreach() in
/www/htdocs/w01a6506/helfer.fachschaftmedizin.de/qualification_functions/qualification_functions.php
on line
503

Warning
: Invalid argument supplied for foreach() in
/www/htdocs/w01a6506/helfer.fachschaftmedizin.de/qualification_functions/qualification_functions.php
on line
503

Warning
: Invalid argument supplied for foreach() in
/www/htdocs/w01a6506/helfer.fachschaftmedizin.de/qualification_functions/qualification_functions.php
on line
503

Warning
: Invalid argument supplied for foreach() in
/www/htdocs/w01a6506/helfer.fachschaftmedizin.de/qualification_functions/qualification_functions.php
on line
50

**Comment by Lockenjoe92** [comment]
Wird durch Fehler im user_bearbeiten für taskforce verursacht.
Da entstehen Datenbankeinträge ohne [] Array-Zeichen. Wenn die da sind, tut der code.
Leo hat für die Ursache schon ein Ticket **#154** aufgemacht:)

**Comment by ldrocket** [comment]
Im Übrigen werden diese "Fehler" unterdrückt, sobald #2 implementiert ist.
