### ISSUE TITLE
Navbar CSS - Informationen und Login verschwinden auf Tablet Größe

### ISSUE THREAD

**Issue by bpcurse** [Lockenjoe92/UKT-COVID19-Helpermanagement#165]
![Screenshot_2020-04-01 UKT COVID-19 Helferkoordinationstool](https://user-images.githubusercontent.com/29312856/78190812-01e4f800-7475-11ea-9a25-9d1b74831692.png)

Das Icon für den Navigation Drawer erscheint erst wieder auf Smartphone Größe

![Screenshot_2020-04-01 UKT COVID-19 Helferkoordinationstool(1)](https://user-images.githubusercontent.com/29312856/78191199-cd257080-7475-11ea-9e0e-c2d3e8ff606a.png)

**Comment by Lockenjoe92** [comment]
ich schau da mal bei Gelegenheit rein - vll kannst du @David100mark  aber nochmal das materialize.css anschauen woran das liegen könnte?

@bpcurse welches Tablet macht da stress?

**Comment by bpcurse** [comment]
Das ist nur mit einem Desktop Firefox auf verschiedenen Größen getestet. Mit einem echten Tablet konnte ich es nicht testen.

**Comment by David100mark** [comment]
Ich schaus mir gleich mal an

**Comment by Lockenjoe92** [comment]
Danke euch!🙂
