### ISSUE TITLE
Default Einstellung für Quali Ja/Nein bei Seite 1 Einteilung anlegen auf „nein“

### ISSUE THREAD

**Issue by Lockenjoe92** [Lockenjoe92/UKT-COVID19-Helpermanagement#174]
Das ist beim debuggen ganz gut alles auf Ja zu haben, aber in der späteren Realität will man wrsl ja eher nur spezifische Qualis -> wäre also schneller für den User nur 1-2 qualis auf Ja zu stellen als alle anderen auf nein.

Vielleicht kann @David100mark da noch seine Erfahrung mit einfließen lassen was besser ist?:)

**Comment by Lockenjoe92** [comment]
Also ich meine die Liste aller qualis die bei der Suche berücksichtigt sein sollen:)

**Comment by David100mark** [comment]
Ja, das wäre gut :)
Also nur falls leerer Array 😁

**Comment by ldrocket** [comment]
Siehe #138.
