### ISSUE TITLE
Helferliste Verfügbarkeit

### ISSUE THREAD

**Issue by David100mark** [Lockenjoe92/UKT-COVID19-Helpermanagement#175]
Hey @JulianFlesch ,
ich bin mir grad bei deinem Code unsicher. Prüfst du bei Verfügbarkeit nur ob der Helfer in Einteilungen angelegt ist?
Weil es müsste tatsächlich geprüft werden ob das Einteilungsende schon vorbei ist.
Ein Helfer kann auch mehrfach eingeteilt werden. Ich glaub Leo hat da schon Code für das anlegen einer Einteilung geschrieben, da ist es ja das gleiche Problem.

**Comment by ldrocket** [comment]
Du kannst ja einfach prüfen, ob es einen Eintrag (oder mehrere) in `einteilungen` gibt und ob einer davon länger geht als die aktuelle Zeit :)

**Comment by JulianFlesch** [comment]
closed in 9fbd83e
