### ISSUE TITLE
Materialize Icons werden nicht mehr angezeigt

### ISSUE THREAD

**Issue by Lockenjoe92** [Lockenjoe92/UKT-COVID19-Helpermanagement#18]
Aktuell im master-playground so:/

**Comment by ldrocket** [comment]
Hmm bei mir werden sie richtig angezeigt. Hab gestern extra die Icons korrigiert, weil sie davor nicht sichtbar waren. Hast du vielleicht Schriftarten bei dir im Browser blockiert?

![Screenshot_2020-03-24 Login - UKT COVID19 Helferkoordinationstool](https://user-images.githubusercontent.com/14164482/77441459-bdf55180-6de9-11ea-805b-3851188029e3.png)

**Comment by Lockenjoe92** [comment]
hmn komisch - bei meinem "privaten" playground gehen die icons bei eigentlich identischem code^^ ich probiere es mal mit nem browser-reboot:D

**Comment by Lockenjoe92** [comment]
Also nach Reboot tut es leider noch nicht - kann es sein, dass ich vielleicht beim Merge irgendwas von dir aus Versehen überschrieben habe?🙈🙈
