### ISSUE TITLE
Abfrage Datenweitergabe extern

### ISSUE THREAD

**Issue by David100mark** [Lockenjoe92/UKT-COVID19-Helpermanagement#182]
neuer Meta key accept_data_transfer: [true,false]?
neuer Meta key accept_data_transfer_date[Date]

--> wenn meta key accept_data_transfer nicht exisitert, dann Abfrage erzwingen, vorher kein Zugriff auf andere Daten
--> Antwort speichern in accept_data_transfer und accept_data_transfer_date anlegen

**Comment by ldrocket** [comment]
Die beiden Felder werden ab sofort durch den CSV-Parser beim Einlesen als leere Felder angelegt, siehe Commit c8c4ee3. D.h., du musst nur noch die Werte der Felder prüfen und dann ggf. updaten :)

**Comment by Lockenjoe92** [comment]
Ansicht und Abfragen für Helfer sind fertig.

**Comment by Lockenjoe92** [comment]
@ldrocket hast du die Überprüfung ob ne Einsatzstelle extern ist und ob die Helfer dem zugestimmt haben schon in die Einteilung-Anlegen Funktionen eingebaut?:)

**Comment by ldrocket** [comment]
Ja, ist bereits implementiert, siehe #186.

**Comment by Lockenjoe92** [comment]
Ah perfekt sry genau den Issue hatte ich vorhin nicht gefunden🙈

Nochmal kurz um sicher zu gehen: wenn dein Code die CSV einließt, legt es das user Meta Feld an, lässt den value aber leer, richtig?:)

**Comment by ldrocket** [comment]
Genau, es legt die leeren Werte `accept_data_transfer_date` und `accept_data_transfer` an.

**Comment by Lockenjoe92** [comment]
Kapiert - dann muss ich schnell was umcoden:);)
