### ISSUE TITLE
Helfer selbst bearbeiten anpassen

### ISSUE THREAD

**Issue by David100mark** [Lockenjoe92/UKT-COVID19-Helpermanagement#187]
erlaube erneute Zustimmung/Ablehnung der Datenweitergabe
siehe #182

**Comment by David100mark** [comment]
Veränderung muss gespeichert werden (vorheriger Zustand und Datum der damaligen Zustimmung/Ablehnung) --> logfile

**Comment by David100mark** [comment]
Funktion add_protocol_entry (log_functions)

**Comment by Lockenjoe92** [comment]
Erledigt:)
