### ISSUE TITLE
Fix saving as CDATA so that edit settings can be implemented 

### ISSUE THREAD

**Issue by Lockenjoe92** [Lockenjoe92/UKT-COVID19-Helpermanagement#199]
Find and implement a way to safely save string input containing HTML from edit_settings to the settings.xml wrapped in CDATA Tags.

**Comment by Lockenjoe92** [comment]
Hey Leute,

Brauche mal kurz eure Unterstützung:
Der HTML-Content einiger Seiten/Erklärungen soll in settings.xml abgespeichert werden.
Dazu habe ich das bereits als CDATA angelegt und wollte nun mit David zusammen die Seite bauen, mit der man als Taskforce-Mitarbeiter diesen HTML-Content editieren kann.

Ich habe dazu bereits in der Funktion update_xml_einstellung() den $mode 'cdata' eingeführt, aber ich finde einfach keinen Weg mit der DOM-Umgebung und der createCDATASection() Funktion den Input aus dem Formular wieder ins .xml Dokument zu speichern....🙈🙈🙈🙈

Kann mir da jemand weiter helfen?:)

LG,
Marc

**Comment by Lockenjoe92** [comment]
@David100mark somit können wir also endlich die Settings-Seite anfangen zu implementieren:)

**Comment by David100mark** [comment]
Sehr gerne :)
