### ISSUE TITLE
Ansicht in Helferauswahl für Einteilung erstellen um Feld erweitern

### ISSUE THREAD

**Issue by Lockenjoe92** [Lockenjoe92/UKT-COVID19-Helpermanagement#220]

**Comment by ldrocket** [comment]
Der in der Datenbank gespeicherte String wird jetzt so in der Einteilungsübersicht angezeigt. Wenn der Wert noch auf ein Wort gemappt werden soll, müsste ich wissen, auf welche :)

**Comment by David100mark** [comment]
Er müsste nur um einen Prozentzeichen ergänzt werden :) und die Überschrift für die Spalte Semester-Verfügbarkeit heißen

**Comment by ldrocket** [comment]
Ist erledigt :+1:
