### ISSUE TITLE
Birthday/Date-Picker spackt auf mobilen Endgeräten

### ISSUE THREAD

**Issue by Lockenjoe92** [Lockenjoe92/UKT-COVID19-Helpermanagement#224]
Beim Verwenden der Datumsauswahl des GB-Pickers funktioniert die Zuordnung der Auswahl nicht korrekt:
-> man will zB 1991 anwählen, es wird aber 1990 oder 1993 eingespeichert.

so passiert auf iPhone 8plus & iPhone SE - aktuelle iOS - Browser: Safari

**Comment by ldrocket** [comment]
Das scheint ein bekannter Bug in Materialize zu sein, siehe https://github.com/Dogfalo/materialize/issues/6476. Es gibt wohl einen Fix, der aber zulasten des Designs geht. Konnte das aber selber nicht testen.

@Lockenjoe92 Wenn der Fix gewünscht ist, einfach in der `main.js` nach der Zeile 32 folgendes einfügen:

`$('.datepicker').addClass('browser-default');`

Dann einfach mal testen und ggf. den Issue nochmal öffnen :)
