### ISSUE TITLE
Helferliste zeigt vorhandenen Vertrag nicht an

### ISSUE THREAD

**Issue by Lockenjoe92** [Lockenjoe92/UKT-COVID19-Helpermanagement#225]
user hat sowohl vertrag "ja" und eine Vertragsnummer hinterlegt - wird aber nicht in der Helferliste so angezeigt.

Siehe User 3 in der aktuellen helfer.fachschaftmedizin.de Datenbank.

**Comment by JulianFlesch** [comment]
Kann ich nicht nachvollziehen, wurde möglicherweise auch in 
1ceaa6f gefixt. 
Bitte nochmal checken ;)
