### ISSUE TITLE
Helferliste zeigt keine Werte für Aufenthaltsort, Einsatzkategorie und Qualifikationen der Helfer an

### ISSUE THREAD

**Issue by Lockenjoe92** [Lockenjoe92/UKT-COVID19-Helpermanagement#228]
Filterfunktion für die drei tut wunderbar, das Ausgeben der Werte in der Tabelle jedoch nicht. Sind leer.

**Comment by JulianFlesch** [comment]
Ich hab mir mal einen aktuellen Datenbank Dump geholt um das zu reproduzieren, auf meinen Testdaten waren die Probleme gefixt.
Soweit ich das grade einschätzen kann, ist das Problem, dass ich auf joins aus den Tabellen "users" und "user_meta" arbeiten muss, um alle Informationen zu bekommen. Aus irgendeinem Grund gibt es in der Datenbank die grade online ist sehr viele Nutzer in "user_meta", die nicht in "users" auftauchen.

**Comment by JulianFlesch** [comment]
Das Trennen von user_meta und user fixt nicht alle Probleme.
