### ISSUE TITLE
Startseiteninhalt in settings.xml anlegen

### ISSUE THREAD

**Issue by Lockenjoe92** [Lockenjoe92/UKT-COVID19-Helpermanagement#27]

**Comment by ldrocket** [comment]
@Lockenjoe92 Hab gesehen, dass ihr die Startseite mit ein paar Infos gefüllt habt. Super :+1: Ist dieser Issue hier dann erledigt?

**Comment by David100mark** [comment]
der Text ist erledigt, aber noch nicht in die Settings.xml übernommen.
Dafür fehlen mir die Skills.

**Comment by ldrocket** [comment]
Aus meiner Sicht kann der Text auch in der Datei `/website_skeleton_functions/startseite_inhalte.php` stehen bleiben. Das ist ja nicht wirklich eine Einstellung, sondern einfach ein Infotext. Oder gibt es andere Gründe?

**Comment by Lockenjoe92** [comment]
Hatte den Hintergrund, dass man den Text, wenn er in settings.xml steht, on the fly auch aus ner schönen User-ansicht heraus ändern kann. Wollte dazu noch ne Seite stricken, aber habs noch nicht implementiert.

Würde das schnell in die settings.xml umbauen:)

**Comment by Lockenjoe92** [comment]
Ist erledigt:)
