### ISSUE TITLE
CSV-Einlesen Email überprüfen

### ISSUE THREAD

**Issue by David100mark** [Lockenjoe92/UKT-COVID19-Helpermanagement#34]
Gib Fehlermeldung aus, wenn keine Email vorhanden oder Email-Adresse ungültig

**Comment by ldrocket** [comment]
Gibt es theoretisch Nutzer, die keine Email haben? Die können wir dann ja auch gar nicht benachrichtigen. Sollen die dann einfach gar nicht importiert werden?

**Comment by David100mark** [comment]
Kann leider theoretisch vorkommen...
Dann einfach nicht importieren :)
Und vllt ne Fehlermeldung ausgeben?

**Comment by ldrocket** [comment]
Eine Warnung vor dem Hochladen sorgt dafür, dass der "Hochlader" sicherstellt, dass die Emails nicht leer oder ungültig sind. Leere oder ungültige Emails werden übersprungen.
