### ISSUE TITLE
Zuweisung Helfer zu Qualifikation mismatch

### ISSUE THREAD

**Issue by Lockenjoe92** [Lockenjoe92/UKT-COVID19-Helpermanagement#35]
Hey Leo,

Problem ist ganz banal, liegt daran, dass ich einfach keine Zeit gefunden hab mich mal mit dir kurz kurzzuschließen wie die Datenbankfelder verknüpft sein sollen🙈

Es war eigentlich so gedacht, dass ein User eine Qualifikation zugewiesen bekommt, indem in der Tabelle das Feld 'has_qualification' angelegt wird und dann als value dazu die ID der jeweiligen Qualifikation aus dem Table 'qualifications' gesetzt wird.

D.h. du müsstest deinen Einlesecode so umbauen, dass er sich die ID für die Qualifikation z.B. anhand des Namens lädt und das dann so einträgt. Vielleicht haust du den David da nochmal an, dass er das mit der Nomenklatur auch in der Excel-Tabelle so macht?:)

Liebe Grüße,
Marc

**Comment by Lockenjoe92** [comment]
Nach als Nachtrag: falls die Qualifikation noch nicht angelegt ist, könntest du auch automatisch die mit der add_qualification Funktion hinzufügen:)

Ähnlich wäre das auch bei den Einsatzkategorien gedacht: also über den Schlüssel 'has_category' auf die jeweilige ID verweisen.

**Comment by ldrocket** [comment]
Closed via #84.

**Comment by ldrocket** [comment]
Closed via #84.
