### ISSUE TITLE
Grundfunktion User bearbeiten TaskForce-View

### ISSUE THREAD

**Issue by Lockenjoe92** [Lockenjoe92/UKT-COVID19-Helpermanagement#39]
- Vorname
- Nachname 
- Mail
- Telefon 
- quali
- Kategorie
- Aufenthaltsort 
- Button: reset pswd

**Comment by SixByNine42** [comment]
Die Daten aus den multiselect-Einträgen werden noch nicht an der Server in $_POST übertragen. In der Helfersuche ist es aber anscheinend schon implementiert.

**Comment by SixByNine42** [comment]
Implementiert in c5789a4e6262d62578ac0308e5633c6d043158e4
(ohne Button: reset pswd)
