### ISSUE TITLE
User bearbeiten TaskForce view - neuen User anlegen

### ISSUE THREAD

**Issue by Lockenjoe92** [Lockenjoe92/UKT-COVID19-Helpermanagement#41]
Händisch User anlegen - zB für neue TaskForce Mitglieder

**Comment by SixByNine42** [comment]
Wenn die Verifizierung der Emailadresse wichtig ist, dann sollte der Account regulär über diese Emailadresse angelegt werden und dann auf der Helfer Bearbeiten-Seite die Rechte erweitert werden.

**Comment by Lockenjoe92** [comment]
Du meinst über das Register.php Formular?

**Comment by SixByNine42** [comment]
Genau

**Comment by SixByNine42** [comment]
Ja.
Falls das heute noch jemand anderes übernimmt:
Ich würde vorschlagen, zum Anlegen eines neuen Users ein kurzes Formular mit den notwendigen Feldern (Name, Vorname, Email) zu erstellen, was die Eingabe aller unerlässlichen Angaben überprüft. Genauso wir in register.php
Wenn das erfolgeich ist, dann kann ein neuer User angelegt werden und die existierende User bearbeiten-Seite für den neuen User angezeigt werden, wo die restlichen Daten eingetragen werden können.

**Comment by Lockenjoe92** [comment]
Finde ich gut - kann man ja auch schnell aus dem reguster.php Code sich bedienen :)

**Comment by SixByNine42** [comment]
Hinweis: Die Taskforce kann versehentlich anlegte User nicht mehr löschen, nur über dropout deaktivieren
