### ISSUE TITLE
Mobile menü funktioniert nicht

### ISSUE THREAD

**Issue by David100mark** [Lockenjoe92/UKT-COVID19-Helpermanagement#42]
Brauchen wir überhaupt ein mobile Menü?

Sonst verlinke ich die login.php einfach als <ul> ?

**Comment by Lockenjoe92** [comment]
Dachte vor allem für die Helfer - da weiß man ja nicht mit welchem endgerät die drauf zugreifen

Ich schau es mir an:)

**Comment by David100mark** [comment]
Ja das dachte ich auch :)
Aber eigentlich brauchen wir nur nen Login/logout-Button oder?
Mehr Funktionen haben wir ja gar nicht

**Comment by Lockenjoe92** [comment]
Fehler lag zum einen in einem Typo von mir und dass das sidenav noch nicht aktiviert war:D jetzt wuppt es einwandfrei:)
