### ISSUE TITLE
Birthday-picker für User

### ISSUE THREAD

**Issue by Lockenjoe92** [Lockenjoe92/UKT-COVID19-Helpermanagement#46]

**Comment by Lockenjoe92** [comment]
Habe das soweit am laufen, aber bin leider bei .js noch recht unerfahren. 
@ldrocket kannst du evtl das noch so umbasteln, dass ein vorhandener Wert, den ich als 'placeholder' mit angebe auch im Kalender als default-value berücksichtigt wird?:)

**Comment by ldrocket** [comment]
@Lockenjoe92 Klar, kann ich machen. In welcher Datei hast du den Kalender eingebaut?

**Comment by Lockenjoe92** [comment]
@ldrocket Geil, danke dir vielmals!:):)

 der Kalender wird in `helper_view_functions.php` auf Zeile 141 aufgerufen.
die Instanz von dem birthday-kauender ist in main.js angelegt (habs dir einfach nachgemacht und die erlaubten Jahreszahlen hochgedreht;))
