### ISSUE TITLE
Datenbankpasswort vor dem Release ändern

### ISSUE THREAD

**Issue by ldrocket** [Lockenjoe92/UKT-COVID19-Helpermanagement#49]
Aktuell ist das Datenbankpasswort hier in GitHub im Klartext sichtbar. Vor dem Release muss es geändert werden (und am besten auch der Datenbankname), auch wenn ein Zugriff nur lokal möglich ist.

**Comment by Lockenjoe92** [comment]
good call!

wir könnten auch das problem lösen indem wir ein dummy `local_db_settings.default.xml` anlegen? so kapiert jeder den code und muss sich dann auf dem eigentlichen server dann daraus eine `local_db_settings.xml` klonen und anpassen?

**Comment by ldrocket** [comment]
Können wir machen, das Passwort bleibt aber weiterhin in der History hier auf GitHub sichtbar. Daher würde ich empfehlen, es vor dem Release zu ändern.

**Comment by bpcurse** [comment]
Auf jeden Fall. Der Datenbankzugriff wird außerdem nur vom localhost möglich sein.

**Comment by Lockenjoe92** [comment]
Jap ich würde dass default file einfach mit pseudo-Werten füllen, dann sind wir komplett Safe:)

**Comment by bpcurse** [comment]
Geändert, das Passwort im repository ist nicht mehr aktuell
