### ISSUE TITLE
Datenbank Struktur ist nicht relational

### ISSUE THREAD

**Issue by JulianFlesch** [Lockenjoe92/UKT-COVID19-Helpermanagement#50]
Wir müssen eventuell unsere Datenbank nochmal überdenken, ich werde da hoffentlich morgen früh ein etwas angepasstes Design in ORM vorlegen können. Aktuell gibt es nach meinem Verständis praktisch keine Referenzen.

Ein Beispiele:
Ein User kann also aktuell keine Qualifikation oder haben oder keine Aufenthaltsorte und kann somit nicht anhand derer gesucht werden.
Es scheint als entsteht die Referenz zwischen einem User und seiner Qualifikation erst über eine Einteilung, aber die versuchen wir ja zu finden, oder?

EDIT: Leo konnte mir erklären, dass man dann über die user_meta.key ein Attribut erhält. Aber das heißt trotzdem, dass ich abhängig vom Key wiederum in verschiedenen Tabellen weitere Queries tätigen muss und das macht den Sinn der Datenbank kaputt.

**Comment by ldrocket** [comment]
In einer zweiten Version wird die Datenbankstruktur überarbeitet.
