### ISSUE TITLE
Impressum & Datenschutzerklärung anlegen

### ISSUE THREAD

**Issue by ldrocket** [Lockenjoe92/UKT-COVID19-Helpermanagement#52]

**Comment by David100mark** [comment]
an welcher Stelle soll ich das einbinden?
ist im Prinzip fertig
(also erstmal für die FS, falls es dann zum UKT kommt müssten die sich was ausdenken.)

**Comment by ldrocket** [comment]
Ich leg dir schnell zwei Dateien an, dann kannst du den Text dahin kopieren.

**Comment by ldrocket** [comment]
Habe die Dateien angelegt. Sobald du den Inhalt eingefügt hast, kannst du den Issue hier schließen :+1:

**Comment by David100mark** [comment]
top, mach ich :)
Den entsprechenden Text im Footer hab ich auch schon angelegt. Aber weiß nicht wie ich den als Link formatiere?

**Comment by ldrocket** [comment]
Ich habe die Seiten schon als Links im Footer angelegt, siehe Commit 0e9d651

Du musst also nur noch den Text einfügen, dann passt alles. Im Anschlúss kannst du den Issue hier schließen.

**Comment by David100mark** [comment]
ah, danke :) jetzt haben wir die Arbeit doppelt gemacht:D
PS: die CSS-Änderungen werden nur sichtbar wenn sie in minimal.css stehen.
