### ISSUE TITLE
Error in csv_upload.php

### ISSUE THREAD

**Issue by Lockenjoe92** [Lockenjoe92/UKT-COVID19-Helpermanagement#6]
Parse error: syntax error, unexpected ':', expecting '{' in /var/www/vhosts/hosting101609.af9a1.netcup.net/ukt-covid-orga-tool-master-playground.marcsprojects.de/csv_import_functions/csv_upload.php on line 2

**Comment by ldrocket** [comment]
Welche PHP-Version hast du bei netcup aktiviert?

**Comment by Lockenjoe92** [comment]
ahhh - 5.6.3 - das wird's wohl gewesen sein:D - kann bis 7.4 gehen, ist das okay für dich?

**Comment by ldrocket** [comment]
Ja perfekt, irgendwas mit 7.x reicht dafür :)

**Comment by Lockenjoe92** [comment]
hin meckert immer noch - hab mal alle features die gehen aktiviert, macht noch keinen unterschied - ich geb dem aber noch 1-2 Minuten um das zu aktualisieren

**Comment by Lockenjoe92** [comment]
okay läuft jetzt!:)

**Comment by Lockenjoe92** [comment]
danke für die schnelle response!:):)

**Comment by ldrocket** [comment]
Top, sehr gerne :)
