### ISSUE TITLE
Rechteüberprüfung

### ISSUE THREAD

**Issue by ldrocket** [Lockenjoe92/UKT-COVID19-Helpermanagement#60]
Prüfen, ob die jeweiligen Seiten nur mit den entsprechenden Berechtigungen aufgerufen werden können. Seiten der Taskforce sollen nur mit der Usermeta `ist_taskforce` aufgerufen werden können.

Reichen die Berechtigungen nicht aus, soll eine entsprechende Fehlermeldung ausgegeben werden im Design der Seite.

**Comment by Lockenjoe92** [comment]
Kann ich schnell erledigen:)

**Comment by Lockenjoe92** [comment]
Habs repariert - session manager schmeißt jetzt zuverlässig raus.
