### ISSUE TITLE
Passwort Qualität sichern

### ISSUE THREAD

**Issue by bpcurse** [Lockenjoe92/UKT-COVID19-Helpermanagement#67]
- Mindestlänge
- Check gegen pwned passwords
- andere Anforderungen

**Comment by ldrocket** [comment]
Eine Implementierung von Dropbox könnte hier zur Qualitätsbestimmung helfen: https://github.com/dropbox/zxcvbn

Bei der Prüfung mit Pwned Passwords bitte nicht das Passwort im Klartext via API übertragen. Erst lokal einen SHA-1-Hash des Passworts bilden, dann die ersten 5 Zeichen dieses Hashes an die API übermitteln, im Anschluss die Rückgabewerte mit dem Eingabewert konkatenieren und prüfen, ob einer der so erzeugen Hashes dem Hash des Passwortes entspricht. Siehe https://haveibeenpwned.com/API/v2#SearchingPwnedPasswordsByRange

Eine andere Möglichkeit ist es, die Hashtabellen lokal zu speichern und zu durchsuchen, aktuell sind das ca. 10 GB.

**Comment by bpcurse** [comment]
Danke für den Hinweis, aber keine Sorge, ich übermittele keine PW an Dritte im Klartext :sweat_smile:
Lieber einmal zu oft warnen ist aber richtig :+1: 
Bei pwned passwords mache ich es wie in der API Doku vorgeschlagen mit den ersten 5 Zeichen des Hashs.
Lokal müsste man die Tabellen ab und zu aktualisieren, ob das bei 10GB sinnvoll ist?
Vielleicht als fallback, wenn beim API die Drosselung greift oder es Verbindungsprobleme gibt?

**Comment by ldrocket** [comment]
Ja genau, war als Hinweis für alle gedacht :smile: 

Wenn ich mich richtig erinnere, gab es früher "Updates" für die Tabellen. Falls es die nicht mehr gibt, müsste man jede x Tage den kompletten Datensatz neu herunterladen, falls man es lokal machen möchte. Da lohnt sich wahrscheinlich der API-Ansatz mehr.

**Comment by bpcurse** [comment]
Soll die Funktion in login_system_parts.php integriert werden? Oder macht ein anderer Ort mehr Sinn? Hab noch nicht so den Überblick.

**Comment by ldrocket** [comment]
Ich würde sie in `/user_functions/user.php` in der Funktion `add_new_user()` implementieren, da kannst du dann auch ggf. eine Fehlermeldung zurückgeben.

**Comment by Lockenjoe92** [comment]
verstehe ich aber richtig, dass die Vertreter der anfordernden Stellen KEIN echtes userkonto bei uns haben sollen, sondern dass wir quasi die stelle selbst wie ein user betrachten der ein shared Secret und ein Passwort hat?

**Comment by Lockenjoe92** [comment]
weil dann würde ich die tabelle in der Datenbank entsprechend erweitern und dann anfangen das ding zu implementieren.
