### ISSUE TITLE
Benutzerangaben beim Editieren als Werte anzeigen

### ISSUE THREAD

**Issue by ldrocket** [Lockenjoe92/UKT-COVID19-Helpermanagement#74]
Aktuell werden Benutzerangaben beim Editieren als Placeholder-Attribut angezeigt. Beim Ändern eines Werts müssen alle Werte neu eingegeben werden. Durch die unmittelbare Anzeige der Werte werden diese beim Speichern überschrieben.

**Comment by SixByNine42** [comment]
Bug ist mit "refix for #57" wieder zurückgekehrt (siehe website_skeleton_functions/bausteine.php Z. 261).
Wir brauchen entweder ein zusätzliches table_form_string_item_prefilled  plus form_string_item_prefilled, oder einen zusätzlichen Parameter "text_in_background=true/false", um zwischen der Beschriftung und dem Vorausfüllen des Formularfelds zu unterscheiden
