### ISSUE TITLE
Verwaltung der Aufenthaltsorte entfernen

### ISSUE THREAD

**Issue by ldrocket** [Lockenjoe92/UKT-COVID19-Helpermanagement#85]
In der CSV-Datei kann es für einen Benutzer mehrere Aufenthaltsorte geben. Das widerspricht der aktuellen Datenbankstruktur, wo es in der Tabelle `user_meta` ein Feld `current_aufenthaltsort` mit der zugehörigen ID gibt. Entweder wir lassen pro Benutzer nur einen exakten Aufenthaltsort zu (was dann aber im Kontrast zur mir vorliegenden CSV-Datei steht) oder wir entfernen die Verwaltung der Aufenthaltsorte und erlauben hier den Freitext.

Ich würde Letzteres empfehlen, da Helfer dann mehrere Orte angeben können zwischen denen sie ggf. wechseln.

**Comment by Lockenjoe92** [comment]
hmn okay das müssen wir mit David abklären, aber klar dann müssen wir was ändern.

**Comment by David100mark** [comment]
also die können tatsächlich mehrere Aufenhaltsorte verwenden. Ich dachte das funktioniert wie has_qualification, wo ja auch mehrere Werte möglich sind?

**Comment by Lockenjoe92** [comment]
Ja würde das sowohl bei Qualifikationen, Aufenthaltsorten und Einsatzkategorien jetzt so machen 

Bei mehreren werten die jeweiligen IDs durch Kommata getrennt
