### ISSUE TITLE
Qualifikationen in Datenbank

### ISSUE THREAD

**Issue by ldrocket** [Lockenjoe92/UKT-COVID19-Helpermanagement#86]
In der Datenbank müssen mindestens die Qualifikationen aus der CSV-Datei enthalten sein und zwar genau in der Schreibweise, wie sie in der Datei stehen. Diese "Standardqualifikationen" dürfen nie entfernt werden (!), ansonsten kommt es beim Anlegen neuer Benutzer und beim Einteilen bestehender Benutzer zu Fehlern.

**Comment by Lockenjoe92** [comment]
Genau das war das Thema was wir mal hatten - wir müssen uns überlegen wie wir das machen: 
1. bleiben die Namen der Qualifikationen in der Excel-Datei so jetzt safe fest?
2. wollen wir die Qualifikationen dann vor dem einlesen anlegen/oder on the fly und gehen somit sicher, dass deine Nomenklatur bestehen bleibt Leo?
3. und klar - löschen wäre dann schlecht:D kann den Knopf auch in der Verwaltung entfernen?

**Comment by ldrocket** [comment]
Kommando zurück! Hier gibt es dasselbe Problem wie in #85.

In der CSV-Datei kann es für einen Benutzer mehrere zweite Qualifikationen ("Qualifikation 2") geben, die sind auch hier kommasepariert. Es kann aber pro Benutzer nur ein Feld `quali2` in der Tabelle `user_meta` geben und nicht mehrere. Das heißt, auch hier müssten wir uns Gedanken über Freitext machen und ob die Verwaltung der Qualis dann überhaupt noch Sinn macht.

**Comment by ldrocket** [comment]
Oder jeder Benutzer kann nur genau eine zweite Quali haben -- was aber in meinen Augen wenig Sinn macht, da es durchaus welche mit mehreren Qualis geben kann.

**Comment by Lockenjoe92** [comment]
nur kurz für blöde: warum kann ich bei der aktuellen Struktur nicht mehrere eintrage mit has_qualification machen und dann jeweils nen anderen wert?

**Comment by ldrocket** [comment]
> nur kurz für blöde: warum kann ich bei der aktuellen Struktur nicht mehrere eintrage mit has_qualification machen und dann jeweils nen anderen wert?

Weil du dann pro Benutzer mehrere Einträge mit demselben Key hast. Wenn ich dann auf einen Benutzer zugreife z.B. mit Benutzer10['has_quali'], welcher der Einträge würde dann genommen werden? :smile:

**Comment by Lockenjoe92** [comment]
ah dang ich dachte dann bekomme ich einfach alle eintrage??🙈🙈🙈

**Comment by Lockenjoe92** [comment]
shit okay das ist natürlich blöd - dann n table user_qualifications aufsetzen?

id - user_id - quali_id

**Comment by Lockenjoe92** [comment]
somit könnte ich dann mehrere Qualis erlauben?

**Comment by ldrocket** [comment]
Ist auf jeden Fall eine gute Idee, find ich persönlich aber nicht so schön, weil wir dann in 3 verschiedenen Tabellen Infos zu den Usern abspeichern :smile:

Was wir machen können ist, dass wir in der Tabelle `user_meta` eine Art Array abspeichern. Das heißt, falls ein Benutzer mehrere Qualis hat, dann wird z.B. nicht nur `3` abgespeichert, sondern `3,5,8`. Ggf. kann man das auch JSON-Wert speichern.

**Comment by Lockenjoe92** [comment]
okay ich verstehe deinen Punkt - ich finde aktuell die Idee mit dem "Array" also einfach die Qualis durch Kommata getrennt gut. Dann passe ich meinen Code entsprechend an und nehme die Löschfunktion raus!:)

**Comment by ldrocket** [comment]
Andere Frage: Für was genau brauchen wir die Verwaltung der Qualis (und in Anlehnung an #85 auch die Verwaltung der Orte)? Wenn es nur darum geht, die Anzahl der jeweiligen Leute herauszufinden, dann können wir das auch anders ermitteln.

Für das Einlesen und Einteilen der Helfer zu Einsatzstellen ist es immer nur sehr aufwendig, weil ich z.B. vom Einteilungsformular die Eingabe "RS ja/nein" erhalte und dann immer erst über die Qualifikationstabelle an die ID kommen muss, um dann zu schauen, ob diese ID beim User hinterlegt ist.

**Comment by ldrocket** [comment]
Wir können ja morgen nochmal miteinander sprechen per Videocall :smile:

**Comment by Lockenjoe92** [comment]
Hintergrund war es einfach auch in Zukunft noch flexibel diese Objekte erweitern zu können, falls da noch was dazukommt - ich verstehe, dass das grad alles n bissl um die Ecke ist und ich freue mich auch schon bei Version von euch mal gezeigt zu bekommen wie man das besser aufsetzt:)

Aber ich finde wenn wir jetzt nochmal all zu viel umwerfen, werden wir nie fertig🙈

**Comment by Lockenjoe92** [comment]
aber im Endeffekt müssen wir das vom David abhängig machen - der weiß was die dudes in der Taskforce tatsächlich wollen:D

**Comment by Lockenjoe92** [comment]
@ldrocket Hab hier mal zwei Funktionen implementiert, die den Abruf der Infos verpacken:

`function parse_qualifications_db_string_to_array($String){

        # Fetches all Qualification Infos for each QualificationID passed in comma-delimited string

        $IDs = explode(',', $String);
        $ReturnArray = array();
        foreach ($IDs as $ID){
            $QualiInfos = fetch_qualification_infos($ID);
            array_push($ReturnArray, $QualiInfos);
        }

        return $ReturnArray;
    }

    function parse_if_qualification_is_in_db_string($SearchQualiID, $String){

        $IDs = explode(',', $String);
        $HitCounter = 0;
        foreach ($IDs as $ID){
            if(intval($SearchQualiID) == intval($ID)){
                $HitCounter++;
            }
        }

        if($HitCounter == 1){
            return true;
        } else {
            return false;
        }
    }`

**Comment by Lockenjoe92** [comment]
@ldrocket kann ich dir iwie was ähnliches stricken um dich beim Einlesen der Daten zu unterstützen?:)

Würde morgen identische Funktionen für die Einsatzkategorien und Aufenthaltsorte basteln

**Comment by ldrocket** [comment]
Ich habe es beim Einlesen etwas vereinfacht, du kannst das so übernehmen: Ich speichere mittels `json_encode()` ein JSON-Objekt in der Datenbank. Wenn du die Daten ausliest, kannst du einfach mit `json_decode()` aus den gespeicherten Daten ein Array erzeugen und es dann weiterverarbeiten: https://www.php.net/manual/de/function.json-decode.php

Damit sparst du dir das manuelle "Zusammensetzen" der Daten zu einem Array, weil du aus den JSON-Daten direkt ein Array generieren kannst.

**Comment by JulianFlesch** [comment]
Die neuen Änderungen müssen nochmal überdacht werden. Das Speichern von mehreren Qualifikationen als String in der Datenbank macht es nahezu unmöglich nach Qualifikationen zu suchen.

In der folgenden Tabelle ist es mir quasi nicht möglich geziehlt nach Qualifikation 3 zu suchen:
+------------------------+----------+
| has_qualifications | "[1,3]"   |
+------------------------+----------+

Was spricht dagegen hier einfach zwei separate has_qualification Keys in der Datenbank zu erstellen? Die Werte können ja nach dem Lesen im PHP Code zu einem Array zusammengefasst werden, nur in der Datenbank ergibt das keinen Sinn.

Die folgende Tabelle löst das Problem für mich:
+------------------------+----------+
| has_qualifications | "1"        |
+------------------------+----------+
| has_qualifications | "3"        |
+------------------------+----------+

Das selbe Problem gibt es natürlich auch für 'aufenthaltsorte' und 'kategorien'.

**Comment by Lockenjoe92** [comment]
Ja das stimmt - ursprünglich hatte ich auch gedacht, dass wir für jede Qualifikation eines Helfers einen Eintrag machen. 

Glaube Leo hat uns dann drauf hingewiesen, dass das mit der Datenbank Probleme gibt wenn man mehrmals den gleichen Schlüssel verwendet. Daher haben wir das so mit den strings jetzt einstweilen gelöst.

In der Tat kann man auf Datenbankebene so nicht direkt suchen. Ich hab das jetzt auf meiner Code-Ebene zB so gelöst:
- ich lade mir einfach alle user_meta Einträge zu has_qualification
-  dann diese Funktion hier:
```

parse_if_qualification_is_in_db_string($SearchQualiID, $String){

        $IDs = explode(',', $String);
        $HitCounter = 0;
        foreach ($IDs as $ID){
            if(intval($SearchQualiID) == intval($ID)){
                $HitCounter++;
            }
        }

        if($HitCounter == 1){
            return true;
        } else {
            return false;
        }
    }

```
- wenn ein User also n True bekommt, kann ich mir dann zB dessen Daten laden und in ein Array speichern.


Ist zwar alles nicht hübsch, aber wie gesagt sollten wir langsam wirklich abliefern. Es ist aktuell letztendlich egal welche der Lösungen wir anstreben, Hauptsache heute oder morgen ist was da mit dem die Leute Anfangen können zu arbeiten.

Wenn ich das jetzt also richtig sehe haben wir drei Ansätze aktuell in Verwendung:
- Leo: JSON String
- Marc: einfach nur ein String -> explode() um diesen in ein Werte-Array zu verwandeln
- Julian: mehrere Datenbankeinträge, einer pro Quali

Wir sollten daher jetzt uns auf eine Herangehensweise einigen:D

Denke die Ansätze von Leo und mir sind relativ gleich und es wäre ein leichtes für mich auch auf JSON umzucoden.

Dein Ansatz Julian könnte ich mit etwas mehr Aufwand auch heute Abend noch eingebaut bekommen.

D.h. ich tät sagen ihr beiden stimmt euch kurz ab wessen Ansatz wir nehmen sollten, aktuell auch im Hinblick welcher ansatz schneller insgesamt umsetzbar ist?

**Comment by David100mark** [comment]
Also ich geb Marc da Recht.Das ist sicher keine optimale Lösung, aber wir müssen jetzt einfach fertig werden.Ich würde dich also bitten, Marc oder Leos Methode zu übernehmen @JulianFlesch

**Comment by JulianFlesch** [comment]
Also die Einträge würden natürlich verschiedene IDs bekommen, lediglich Nutzer und schlüssel währen gleich.
Ich werd das dann aber nach der aktuellen Methode umsetzen, danke für eure Hilfe!

**Comment by Lockenjoe92** [comment]
Läuft, danke auch dir lieber Julian!:)

Freue mich schon auf Version 2.0 - und vor allem, dass wir da Zeit haben zuerst alles zu planen und dann erst zu handeln:D

**Comment by Lockenjoe92** [comment]
@Julian - welche Variante verwendest du nochmal genau? 
JSON nach Leo oder String-explode() von mir?

**Comment by Lockenjoe92** [comment]
Nur damit Leo oder ich unseren Code anpassen.

Denn wenn ich richtig verstehe, sehen die strings ja leicht anders aus:
- Leo: [1,2]
- Marc: 1,2

Müssten uns also da auf Leos oder meine Variante einigen - mir ist das egal und ich kann meinen Code denke ich mit recht wenig Aufwand auf JSON umändern wenn’s wär.

**Comment by ldrocket** [comment]
> ich kann meinen Code denke ich mit recht wenig Aufwand auf JSON umändern wenn’s wär.

Du müsstest eigentlich nur die Zeile

` $IDs = explode(',', $String);`

ändern in

` $IDs = json_decode($String);`

(Habs nicht getestet, aber grob sollte das stimmen)

**Comment by Lockenjoe92** [comment]
Genau deswegen mache ich mir keine Sorgen das schnell umgebaut zu bekommen:)

Nur wollte ich hier kurz abchecken dass wir wirklich alle JSON verwenden und Julian nicht doch auf die String-Variante von mir geht:D

**Comment by Lockenjoe92** [comment]
Würde dann dem Frédérik auch Bescheid geben welche Variante wir fahren:)

**Comment by JulianFlesch** [comment]
Um hier zur Übersicht beizutragen: Ich benutze auch die JSON methode :P

**Comment by Lockenjoe92** [comment]
Alles klar dann schraube ich meinen Code auch auf JSON um:)

**Comment by Lockenjoe92** [comment]
hab meinen code angepasst - sollte nun tun:)
