### ISSUE TITLE
Fehlermeldung beim versenden von Mails

### ISSUE THREAD

**Issue by David100mark** [Lockenjoe92/UKT-COVID19-Helpermanagement#87]
Warning
: simplexml_load_file(): ./mail_generation_functions/mailvorlagen.xml:1: parser error : Document labelled UTF-16 but has UTF-8 content in
/mail_generation_functions/mailvorlagen.php

**Comment by Lockenjoe92** [comment]
Vielleicht kann sich Torsten auch da reinfuchsen?:)

**Comment by Lockenjoe92** [comment]
Vielleicht reicht es das content einfach wieder oben im xml file als utf8 zu markieren?

**Comment by ldrocket** [comment]
Solange die Mails trotzdem versendet werden, ist das kein Problem. Das ist nur eine Warnung, weil die XML-Datei vermutlich als UTF-16 angelegt ist. Man kann die Kodierung ändern, dann sollte der Fehler verschwinden. Sobald die PHP-Fehlermeldungen vor dem Veröffentlichen via #2 abgeschaltet werden, verschwindet diese Meldung sowieso.

**Comment by David100mark** [comment]
also die Mails werden nicht verschickt...

**Comment by ldrocket** [comment]
Von welcher Seite aus hast du die E-Mails verschickt? Und bei welcher Aktion?

**Comment by David100mark** [comment]
Einmal Anlegen einer Stelle und beim Zuteilung von mir zu einer Stelle

**Comment by ldrocket** [comment]
Auf welcher URL hast dus probiert?

**Comment by David100mark** [comment]
auf dem Masterplayground

**Comment by ldrocket** [comment]
Habe es gerade nochmal getestet und konnte das Problem nicht reproduzieren. Alle Mails werden korrekt versendet. Vermutlich wurde das mit Commit c304f18 geschlossen.
