### ISSUE TITLE
Zurück-Buttons im Einteilung-Anlegen Formular

### ISSUE THREAD

**Issue by Lockenjoe92** [Lockenjoe92/UKT-COVID19-Helpermanagement#89]
In dem, extrem geilen:-), Formular gibt es für den User noch keine zurück-knöpfe. Insbesondere nach dem erfolgreichen Einteilen der User wär das cool, damit die Benutzer nicht anfangen mit der Zurück-Taste des Browsers zu spielen?:)

LG:)

**Comment by ldrocket** [comment]
Ja ich weiß, danke fürs Erinnern. Kommt noch :smile:

**Comment by Lockenjoe92** [comment]
okay:) sry wollt nicht stressen🙈🙈

**Comment by ldrocket** [comment]
Hab ich auch nicht so aufgefasst :)
