### ISSUE TITLE
Fehler beim csv upload

### ISSUE THREAD

**Issue by David100mark** [Lockenjoe92/UKT-COVID19-Helpermanagement#95]
Fatal error: Uncaught Error: Call to a member function fetch_row() on bool in /csv_import_functions/csv_upload.php:152 Stack trace: #0  csv_upload.php(8): csv_upload_parser() #1 {main} thrown in csv_import_functions/csv_upload.php on line 152

getestet auf dem Master-Playground

Emails an die Helfer werden trotzdem verschickt

**Comment by ldrocket** [comment]
Kannst du mir die Datei schicken, mit der du es getestet hast?

**Comment by David100mark** [comment]
Klar :)
________________________________

**Comment by ldrocket** [comment]
Konnte das leider nicht reproduzieren. Bitte nochmal testen und falls es weiterhin auftritt einfach den Issue wieder eröffnen :)
