### ISSUE TITLE
Passwort vergessen

### ISSUE THREAD

**Issue by ldrocket** [Lockenjoe92/UKT-COVID19-Helpermanagement#96]
Aktuell gibt es noch keine Funktion für "Passwort vergessen". Vorschlag: Wir handhaben das gleich wie beim ersten Setzen des Passworts via CSV-Uploader. Das heißt, dass ein Benutzer beim Anfordern eines neuen Passworts dieses per E-Mail zugeschickt bekommt und es nach dem Anmelden wieder ändern muss.

**Comment by David100mark** [comment]
Find ich nen sinnvolles vorgehen :)

**Comment by Lockenjoe92** [comment]
passt - da hab ich noch ne staubige vorlage aus stocherkahnzeiten dafür;) wird gebastelt!:)

**Comment by ldrocket** [comment]
Danke dir :+1:

**Comment by Lockenjoe92** [comment]
erledigt:)
