### ISSUE TITLE
Bug beim Parsen von Seite 2 des Einteilungsformulars

### ISSUE THREAD

**Issue by Lockenjoe92** [Lockenjoe92/UKT-COVID19-Helpermanagement#98]
Warning
: implode(): Invalid arguments passed in
/var/www/vhosts/hosting101609.af9a1.netcup.net/marc-ukt-dev-playground.marcsprojects.de/mission_functions/mission_manage.php
on line
129

**Comment by Lockenjoe92** [comment]
ist mit aktuellem code gelaufen - soll ich dir die verwendeten Parameter noch hinschreiben?:)

**Comment by ldrocket** [comment]
Das hängt damit zusammen, dass in den Testdaten nicht für alle Benutzer alle Metadaten hinterlegt sind. Wenn alle Metadaten korrekt vorhanden sind, verschwindet der Fehler :)

**Comment by Lockenjoe92** [comment]
Ah okay, alles klar:)
